### ISSUE TITLE
Inline svg with emblem.js

### ISSUE THREAD

**Issue by cjroebuck** [machty/emblem.js#153]
Hey,

Is there a way to tell emblem to drop down to regular HTML. I want to include some inline svg in an emblem template but don't want to have to reformat it each time, also I'm not even sure ember supports the svg tag at the moment. If there is a better way to do this, please let me know. 

(PS I don't want to use the svg as an image, it needs to be inline for my requirements so that I can target specific elements using css.)

**Comment by CNDW** [comment]
you should be able to just put the svg tag content after a pipe, I.E.

```
 | <svg>
    ...svg content
  </svg>
```

I know that handlebars and ember have not played nicely with SVG content, [until recently](https://github.com/emberjs/ember.js/issues/5021). I'm not sure how things have changed since htmlbars, I'd be interested in looking into it once emblem compatibility with html bars is finished.
