### ISSUE TITLE
Deploy master to NPM

### ISSUE THREAD

**Issue by saponifi3d** [machty/emblem.js#197]
@machty - would it be possible to put what is currently master on NPM - the conversion to handlebars 2.0.0 will solve a lot of bugs that keep happening w/ emblem. (I'm also waiting for it to update gulp-emblem and grunt-emblem for handlebars 2.0.0).

Thanks :)

**Comment by machty** [comment]
Done, lemme know if I messed something up

**Comment by saponifi3d** [comment]
:D thanks!!!

**Comment by bjornstar** [comment]
Changing handlebars 1.3.0 to 2.0.0 is not a patch level change. Please delete 0.3.19 from npm and release it as 0.4.0 so that people still stuck on handlebars 1.3.0 can use 0.3.x and people in the modern age can use 0.4.x for handlebars 2.0.0

Also, please add a tag to the repo for 0.4.0 when you release that.

**Comment by bantic** [comment]
@bjornstar 0.3.19 doesn't target Handlebars 2.0.0. That support is coming, but it is not in master yet.

**Comment by bantic** [comment]
@bjornstar Nope, I'm wrong, sorry: https://github.com/machty/emblem.js/commit/54d4e8759a078eb01f4a85e6bf572eeaf449b406
